language: node_js

node_js:
  - lts/*

cache:
  directories:
    - ~/.npm

notifications:
  email: false

jobs:
  include:
    - stage: test
      script:
        - npm run test
      # before_script: greenkeeper-lockfile-update
      # after_script: greenkeeper-lockfile-upload
      # after_success: npm run codecov

    # Define the release stage that runs semantic-release
    - stage: release
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
        after_success:
          - npm run gulp:deploy
