language: node_js

node_js:
  - lts/*

cache:
  npm: true
  directories:
    - ./dist

notifications:
  email: false

jobs:
  include:
    - stage: build
      script:
        - npm run build

    - stage: test
      script:
        - npm run test

    - stage: release
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script:
          - npx semantic-release
